### ISSUE TITLE
Could not find reline-0.5.12 in locally installed gems

### ISSUE THREAD

**Issue by vfonic** [mattbrictson/bundle_update_interactive#65]
When I run `bundle ui` without `reline` 0.5.12, I get the following error*:

```sh
 > bundle ui         
Resolving latest gem versions...
Could not find reline-0.5.12 in locally installed gems
/Users/viktor/.rvm/gems/ruby-3.3.4/gems/bundle_update_interactive-0.10.0/lib/bundle_update_interactive/bundler_commands.rb:32:in `parse_outdated': bundle outdated command failed (RuntimeError)
        from /Users/viktor/.rvm/gems/ruby-3.3.4/gems/bundle_update_interactive-0.10.0/lib/bundle_update_interactive/updater.rb:67:in `find_withheld_gems'
        from /Users/viktor/.rvm/gems/ruby-3.3.4/gems/bundle_update_interactive-0.10.0/lib/bundle_update_interactive/updater.rb:14:in `generate_report'
        from /Users/viktor/.rvm/gems/ruby-3.3.4/gems/bundle_update_interactive-0.10.0/lib/bundle_update_interactive/cli.rb:66:in `generate_report'
        from /Users/viktor/.rvm/gems/ruby-3.3.4/gems/bundle_update_interactive-0.10.0/lib/bundle_update_interactive/cli.rb:9:in `run'
        from /Users/viktor/.rvm/gems/ruby-3.3.4/gems/bundle_update_interactive-0.10.0/exe/bundler-ui:6:in `<top (required)>'
        from /Users/viktor/.rvm/gems/ruby-3.3.4/bin/bundler-ui:25:in `load'
        from /Users/viktor/.rvm/gems/ruby-3.3.4/bin/bundler-ui:25:in `<main>'
        from /Users/viktor/.rvm/gems/ruby-3.3.4/bin/ruby_executable_hooks:22:in `eval'
        from /Users/viktor/.rvm/gems/ruby-3.3.4/bin/ruby_executable_hooks:22:in `<main>'


> gem install reline --version 0.5.12
Fetching reline-0.5.12.gem
Successfully installed reline-0.5.12
1 gem installed


> bundle ui                          
Resolving latest gem versions...
Checking for security vulnerabilities...
Finding changelogs........
```

*I tried running `gem install reline` which installed reline 0.6.0 and I was still seeing the same error.

**Comment by mattbrictson** [comment]
It looks like the error occurred while `update-interactive` was internally running `bundle outdated`. I wonder, are you able to reproduce an error running `bundle outdated` directly? You may need to uninstall reline 0.5.12 to get back to the original state where the problem is.

**Comment by vfonic** [comment]
I noticed that I was running this in a Rails project that has reline 0.5.12 in `Gemfile.lock`

**Comment by vfonic** [comment]
I don't know if bundler has some local caching.

```sh
 > bundler --version
Bundler version 2.5.15
```

**Comment by mattbrictson** [comment]
Interesting. What about `bundle outdated --parseable`? Does that fail with any errors?

If you don't mind sharing your `Gemfile` and `Gemfile.lock`, I could use them to try to reproduce the error on my side and troubleshoot further.

**Comment by vfonic** [comment]
Here's one new Rails 8 project with a small `Gemfile` where `bundle ui` is failing if I don't run `bundle install` (w/o reline), but `bundle outdated --parseable` doesn't fail:

<details><summary>Gemfile</summary>

```ruby
source "https://rubygems.org"

ruby file: ".ruby-version"

# Rails fundamentals [https://evilmartians.com/chronicles/gemfile-of-dreams-libraries-we-use-to-build-rails-apps#rails-fundamentals]
gem "bootsnap", require: false # Reduces boot times through caching; required in config/boot.rb
gem "pg", "~> 1.1" # PostgreSQL as the database for Active Record
gem "puma", ">= 5.0" # Puma web server [https://github.com/puma/puma]
gem "rails", "~> 8.0.0"

# translation
gem "devise-i18n"
gem "kaminari-i18n"
gem "rails-i18n"

# deployment
gem "kamal", require: false # Deploy this application anywhere as a Docker container [https://kamal-deploy.org]
gem "thruster", require: false # Add HTTP asset caching/compression and X-Sendfile acceleration to Puma [https://github.com/basecamp/thruster/]

# misc
gem "tzinfo-data", platforms: %i[windows jruby] # Windows does not include zoneinfo files, so bundle the tzinfo-data gem
# Active Model has_secure_password [https://guides.rubyonrails.org/active_model_basics.html#securepassword]
# gem "bcrypt", "~> 3.1.7"

# asset management
gem "cssbundling-rails" # used by activeadmin for tailwindcss
gem "importmap-rails" # JavaScript with ESM import maps [https://github.com/rails/importmap-rails]
gem "jbuilder" # Build JSON APIs with ease [https://github.com/rails/jbuilder]
gem "propshaft" # The modern asset pipeline for Rails [https://github.com/rails/propshaft]
gem "stimulus-rails" # Hotwire's modest JavaScript framework [https://stimulus.hotwired.dev]
gem "turbo-rails" # Hotwire's SPA-like page accelerator [https://turbo.hotwired.dev]

gem "hotwire_combobox"

gem "solid_cable" # database-backed adapter for Action Cable
gem "solid_cache" # database-backed adapter for Rails.cache
gem "solid_queue" # database-backed adapter for Active Job

# Active Storage variants [https://guides.rubyonrails.org/active_storage_overview.html#transforming-images]
# gem "image_processing", "~> 1.2"

group :development, :test do
  gem "brakeman", require: false # Static analysis for security vulnerabilities [https://brakemanscanner.org/]
  gem "bundler-audit", require: false
  gem "database_consistency", require: false
  gem "debug", platforms: %i[mri windows], require: "debug/prelude" # See https://guides.rubyonrails.org/debugging_rails_applications.html#debugging-with-the-debug-gem
  gem "erb_lint"
  gem "rubocop-capybara", require: false
  gem "stylecheck", github: "vfonic/stylecheck", require: false
end

group :development do
  gem "overmind" # Foreman replacement [https://github.com/DarthSim/overmind]
  gem "web-console" # Console on exceptions pages [https://github.com/rails/web-console]
end

group :test do
  # System testing [https://guides.rubyonrails.org/testing.html#system-testing]
  gem "capybara"
  gem "selenium-webdriver"
end

gem "activeadmin", "~> 4.0.0.beta7"
gem "devise"
gem "pundit"

gem "fancy_irb", "~> 2.1"

# Fly.io
gem "aws-sdk-s3", "~> 1.176", require: false
gem "dockerfile-rails", ">= 1.6", group: :development
```

</details>


<details><summary>Gemfile.lock</summary>

```
GIT
  remote: https://github.com/vfonic/stylecheck.git
  revision: c2ce941cf8df42a0e9fc9e206033860f775b1381
  specs:
    stylecheck (20.0.0)
      database_validations
      rake
      rubocop
      rubocop-factory_bot
      rubocop-obsession
      rubocop-performance
      rubocop-rails
      rubocop-rake
      rubocop-rspec
      rubocop-rspec_rails

GEM
  remote: https://rubygems.org/
  specs:
    actioncable (8.0.1)
      actionpack (= 8.0.1)
      activesupport (= 8.0.1)
      nio4r (~> 2.0)
      websocket-driver (>= 0.6.1)
      zeitwerk (~> 2.6)
    actionmailbox (8.0.1)
      actionpack (= 8.0.1)
      activejob (= 8.0.1)
      activerecord (= 8.0.1)
      activestorage (= 8.0.1)
      activesupport (= 8.0.1)
      mail (>= 2.8.0)
    actionmailer (8.0.1)
      actionpack (= 8.0.1)
      actionview (= 8.0.1)
      activejob (= 8.0.1)
      activesupport (= 8.0.1)
      mail (>= 2.8.0)
      rails-dom-testing (~> 2.2)
    actionpack (8.0.1)
      actionview (= 8.0.1)
      activesupport (= 8.0.1)
      nokogiri (>= 1.8.5)
      rack (>= 2.2.4)
      rack-session (>= 1.0.1)
      rack-test (>= 0.6.3)
      rails-dom-testing (~> 2.2)
      rails-html-sanitizer (~> 1.6)
      useragent (~> 0.16)
    actiontext (8.0.1)
      actionpack (= 8.0.1)
      activerecord (= 8.0.1)
      activestorage (= 8.0.1)
      activesupport (= 8.0.1)
      globalid (>= 0.6.0)
      nokogiri (>= 1.8.5)
    actionview (8.0.1)
      activesupport (= 8.0.1)
      builder (~> 3.1)
      erubi (~> 1.11)
      rails-dom-testing (~> 2.2)
      rails-html-sanitizer (~> 1.6)
    activeadmin (4.0.0.beta15)
      arbre (~> 2.0)
      csv
      formtastic (>= 3.1)
      formtastic_i18n (>= 0.4)
      inherited_resources (~> 2.0)
      kaminari (>= 1.2.1)
      railties (>= 7.0)
      ransack (>= 4.0)
    activejob (8.0.1)
      activesupport (= 8.0.1)
      globalid (>= 0.3.6)
    activemodel (8.0.1)
      activesupport (= 8.0.1)
    activerecord (8.0.1)
      activemodel (= 8.0.1)
      activesupport (= 8.0.1)
      timeout (>= 0.4.0)
    activestorage (8.0.1)
      actionpack (= 8.0.1)
      activejob (= 8.0.1)
      activerecord (= 8.0.1)
      activesupport (= 8.0.1)
      marcel (~> 1.0)
    activesupport (8.0.1)
      base64
      benchmark (>= 0.3)
      bigdecimal
      concurrent-ruby (~> 1.0, >= 1.3.1)
      connection_pool (>= 2.2.5)
      drb
      i18n (>= 1.6, < 2)
      logger (>= 1.4.2)
      minitest (>= 5.1)
      securerandom (>= 0.3)
      tzinfo (~> 2.0, >= 2.0.5)
      uri (>= 0.13.1)
    addressable (2.8.7)
      public_suffix (>= 2.0.2, < 7.0)
    arbre (2.0.2)
      activesupport (>= 3.0.0)
    ast (2.4.2)
    aws-eventstream (1.3.0)
    aws-partitions (1.1018.0)
    aws-sdk-core (3.214.0)
      aws-eventstream (~> 1, >= 1.3.0)
      aws-partitions (~> 1, >= 1.992.0)
      aws-sigv4 (~> 1.9)
      jmespath (~> 1, >= 1.6.1)
    aws-sdk-kms (1.96.0)
      aws-sdk-core (~> 3, >= 3.210.0)
      aws-sigv4 (~> 1.5)
    aws-sdk-s3 (1.176.0)
      aws-sdk-core (~> 3, >= 3.210.0)
      aws-sdk-kms (~> 1)
      aws-sigv4 (~> 1.5)
    aws-sigv4 (1.10.1)
      aws-eventstream (~> 1, >= 1.0.2)
    base64 (0.2.0)
    bcrypt (3.1.20)
    bcrypt_pbkdf (1.1.1)
    bcrypt_pbkdf (1.1.1-arm64-darwin)
    bcrypt_pbkdf (1.1.1-x86_64-darwin)
    benchmark (0.4.0)
    better_html (2.1.1)
      actionview (>= 6.0)
      activesupport (>= 6.0)
      ast (~> 2.0)
      erubi (~> 1.4)
      parser (>= 2.4)
      smart_properties
    bigdecimal (3.1.8)
    bindex (0.8.1)
    bootsnap (1.18.4)
      msgpack (~> 1.2)
    brakeman (6.2.2)
      racc
    builder (3.3.0)
    bundler-audit (0.9.2)
      bundler (>= 1.2.0, < 3)
      thor (~> 1.0)
    capybara (3.40.0)
      addressable
      matrix
      mini_mime (>= 0.1.3)
      nokogiri (~> 1.11)
      rack (>= 1.6.0)
      rack-test (>= 0.6.3)
      regexp_parser (>= 1.5, < 3.0)
      xpath (~> 3.2)
    concurrent-ruby (1.3.4)
    connection_pool (2.4.1)
    crass (1.0.6)
    cssbundling-rails (1.4.1)
      railties (>= 6.0.0)
    csv (3.3.0)
    database_consistency (1.7.26)
      activerecord (>= 3.2)
    database_validations (1.1.1)
      activerecord (>= 4.2.0)
    date (3.4.1)
    debug (1.9.2)
      irb (~> 1.10)
      reline (>= 0.3.8)
    devise (4.9.4)
      bcrypt (~> 3.0)
      orm_adapter (~> 0.1)
      railties (>= 4.1.0)
      responders
      warden (~> 1.2.3)
    devise-i18n (1.12.1)
      devise (>= 4.9.0)
    dockerfile-rails (1.6.24)
      rails (>= 3.0.0)
    dotenv (3.1.6)
    drb (2.2.1)
    ed25519 (1.3.0)
    erb_lint (0.7.0)
      activesupport
      better_html (>= 2.0.1)
      parser (>= 2.7.1.4)
      rainbow
      rubocop (>= 1)
      smart_properties
    erubi (1.13.0)
    et-orbi (1.2.11)
      tzinfo
    fancy_irb (2.1.2)
      irb (>= 1.7, < 2.0)
      paint (>= 0.9, < 3.0)
      unicode-display_width (>= 2.5)
    formtastic (5.0.0)
      actionpack (>= 6.0.0)
    formtastic_i18n (0.7.0)
    fugit (1.11.1)
      et-orbi (~> 1, >= 1.2.11)
      raabro (~> 1.4)
    globalid (1.2.1)
      activesupport (>= 6.1)
    has_scope (0.8.2)
      actionpack (>= 5.2)
      activesupport (>= 5.2)
    hotwire_combobox (0.3.2)
      rails (>= 7.0.7.2)
      stimulus-rails (>= 1.2)
      turbo-rails (>= 1.2)
    i18n (1.14.6)
      concurrent-ruby (~> 1.0)
    importmap-rails (2.0.3)
      actionpack (>= 6.0.0)
      activesupport (>= 6.0.0)
      railties (>= 6.0.0)
    inherited_resources (2.1.0)
      actionpack (>= 7.0)
      has_scope (>= 0.6)
      railties (>= 7.0)
      responders (>= 2)
    io-console (0.8.0)
    irb (1.14.2)
      rdoc (>= 4.0.0)
      reline (>= 0.4.2)
    jbuilder (2.13.0)
      actionview (>= 5.0.0)
      activesupport (>= 5.0.0)
    jmespath (1.6.2)
    json (2.7.5)
    kamal (2.4.0)
      activesupport (>= 7.0)
      base64 (~> 0.2)
      bcrypt_pbkdf (~> 1.0)
      concurrent-ruby (~> 1.2)
      dotenv (~> 3.1)
      ed25519 (~> 1.2)
      net-ssh (~> 7.3)
      sshkit (>= 1.23.0, < 2.0)
      thor (~> 1.3)
      zeitwerk (>= 2.6.18, < 3.0)
    kaminari (1.2.2)
      activesupport (>= 4.1.0)
      kaminari-actionview (= 1.2.2)
      kaminari-activerecord (= 1.2.2)
      kaminari-core (= 1.2.2)
    kaminari-actionview (1.2.2)
      actionview
      kaminari-core (= 1.2.2)
    kaminari-activerecord (1.2.2)
      activerecord
      kaminari-core (= 1.2.2)
    kaminari-core (1.2.2)
    kaminari-i18n (0.5.0)
      kaminari
      rails
    language_server-protocol (3.17.0.3)
    logger (1.6.3)
    loofah (2.23.1)
      crass (~> 1.0.2)
      nokogiri (>= 1.12.0)
    mail (2.8.1)
      mini_mime (>= 0.1.1)
      net-imap
      net-pop
      net-smtp
    marcel (1.0.4)
    matrix (0.4.2)
    mini_mime (1.1.5)
    minitest (5.25.4)
    msgpack (1.7.3)
    net-imap (0.5.1)
      date
      net-protocol
    net-pop (0.1.2)
      net-protocol
    net-protocol (0.2.2)
      timeout
    net-scp (4.0.0)
      net-ssh (>= 2.6.5, < 8.0.0)
    net-sftp (4.0.0)
      net-ssh (>= 5.0.0, < 8.0.0)
    net-smtp (0.5.0)
      net-protocol
    net-ssh (7.3.0)
    nio4r (2.7.4)
    nokogiri (1.17.2-aarch64-linux)
      racc (~> 1.4)
    nokogiri (1.17.2-arm-linux)
      racc (~> 1.4)
    nokogiri (1.17.2-arm64-darwin)
      racc (~> 1.4)
    nokogiri (1.17.2-x86-linux)
      racc (~> 1.4)
    nokogiri (1.17.2-x86_64-darwin)
      racc (~> 1.4)
    nokogiri (1.17.2-x86_64-linux)
      racc (~> 1.4)
    orm_adapter (0.5.0)
    ostruct (0.6.1)
    overmind (2.5.1)
    overmind (2.5.1-aarch64-linux)
    overmind (2.5.1-arm-linux)
    overmind (2.5.1-arm64-darwin)
    overmind (2.5.1-x86-linux)
    overmind (2.5.1-x86_64-darwin)
    paint (2.3.0)
    parallel (1.26.3)
    parser (3.3.5.1)
      ast (~> 2.4.1)
      racc
    pg (1.5.9)
    propshaft (1.1.0)
      actionpack (>= 7.0.0)
      activesupport (>= 7.0.0)
      rack
      railties (>= 7.0.0)
    psych (5.2.1)
      date
      stringio
    public_suffix (6.0.1)
    puma (6.4.3)
      nio4r (~> 2.0)
    pundit (2.4.0)
      activesupport (>= 3.0.0)
    raabro (1.4.0)
    racc (1.8.1)
    rack (3.1.8)
    rack-session (2.0.0)
      rack (>= 3.0.0)
    rack-test (2.1.0)
      rack (>= 1.3)
    rackup (2.2.1)
      rack (>= 3)
    rails (8.0.1)
      actioncable (= 8.0.1)
      actionmailbox (= 8.0.1)
      actionmailer (= 8.0.1)
      actionpack (= 8.0.1)
      actiontext (= 8.0.1)
      actionview (= 8.0.1)
      activejob (= 8.0.1)
      activemodel (= 8.0.1)
      activerecord (= 8.0.1)
      activestorage (= 8.0.1)
      activesupport (= 8.0.1)
      bundler (>= 1.15.0)
      railties (= 8.0.1)
    rails-dom-testing (2.2.0)
      activesupport (>= 5.0.0)
      minitest
      nokogiri (>= 1.6)
    rails-html-sanitizer (1.6.2)
      loofah (~> 2.21)
      nokogiri (>= 1.15.7, != 1.16.7, != 1.16.6, != 1.16.5, != 1.16.4, != 1.16.3, != 1.16.2, != 1.16.1, != 1.16.0.rc1, != 1.16.0)
    rails-i18n (8.0.1)
      i18n (>= 0.7, < 2)
      railties (>= 8.0.0, < 9)
    railties (8.0.1)
      actionpack (= 8.0.1)
      activesupport (= 8.0.1)
      irb (~> 1.13)
      rackup (>= 1.0.0)
      rake (>= 12.2)
      thor (~> 1.0, >= 1.2.2)
      zeitwerk (~> 2.6)
    rainbow (3.1.1)
    rake (13.2.1)
    ransack (4.2.1)
      activerecord (>= 6.1.5)
      activesupport (>= 6.1.5)
      i18n
    rdoc (6.9.0)
      psych (>= 4.0.0)
    regexp_parser (2.9.2)
    reline (0.5.12)
      io-console (~> 0.5)
    responders (3.1.1)
      actionpack (>= 5.2)
      railties (>= 5.2)
    rexml (3.3.9)
    rubocop (1.68.0)
      json (~> 2.3)
      language_server-protocol (>= 3.17.0)
      parallel (~> 1.10)
      parser (>= 3.3.0.2)
      rainbow (>= 2.2.2, < 4.0)
      regexp_parser (>= 2.4, < 3.0)
      rubocop-ast (>= 1.32.2, < 2.0)
      ruby-progressbar (~> 1.7)
      unicode-display_width (>= 2.4.0, < 3.0)
    rubocop-ast (1.33.0)
      parser (>= 3.3.1.0)
    rubocop-capybara (2.21.0)
      rubocop (~> 1.41)
    rubocop-factory_bot (2.26.1)
      rubocop (~> 1.61)
    rubocop-obsession (0.1.5)
      activesupport
      rubocop (~> 1.41)
    rubocop-performance (1.22.1)
      rubocop (>= 1.48.1, < 2.0)
      rubocop-ast (>= 1.31.1, < 2.0)
    rubocop-rails (2.27.0)
      activesupport (>= 4.2.0)
      rack (>= 1.1)
      rubocop (>= 1.52.0, < 2.0)
      rubocop-ast (>= 1.31.1, < 2.0)
    rubocop-rake (0.6.0)
      rubocop (~> 1.0)
    rubocop-rspec (3.2.0)
      rubocop (~> 1.61)
    rubocop-rspec_rails (2.30.0)
      rubocop (~> 1.61)
      rubocop-rspec (~> 3, >= 3.0.1)
    ruby-progressbar (1.13.0)
    rubyzip (2.3.2)
    securerandom (0.4.0)
    selenium-webdriver (4.26.0)
      base64 (~> 0.2)
      logger (~> 1.4)
      rexml (~> 3.2, >= 3.2.5)
      rubyzip (>= 1.2.2, < 3.0)
      websocket (~> 1.0)
    smart_properties (1.17.0)
    solid_cable (3.0.2)
      actioncable (>= 7.2)
      activejob (>= 7.2)
      activerecord (>= 7.2)
      railties (>= 7.2)
    solid_cache (1.0.6)
      activejob (>= 7.2)
      activerecord (>= 7.2)
      railties (>= 7.2)
    solid_queue (1.0.0)
      activejob (>= 7.1)
      activerecord (>= 7.1)
      concurrent-ruby (>= 1.3.1)
      fugit (~> 1.11.0)
      railties (>= 7.1)
      thor (~> 1.3.1)
    sshkit (1.23.2)
      base64
      net-scp (>= 1.1.2)
      net-sftp (>= 2.1.2)
      net-ssh (>= 2.8.0)
      ostruct
    stimulus-rails (1.3.4)
      railties (>= 6.0.0)
    stringio (3.1.2)
    thor (1.3.2)
    thruster (0.1.8)
    thruster (0.1.8-aarch64-linux)
    thruster (0.1.8-arm64-darwin)
    thruster (0.1.8-x86_64-darwin)
    thruster (0.1.8-x86_64-linux)
    timeout (0.4.2)
    turbo-rails (2.0.11)
      actionpack (>= 6.0.0)
      railties (>= 6.0.0)
    tzinfo (2.0.6)
      concurrent-ruby (~> 1.0)
    unicode-display_width (2.6.0)
    uri (1.0.2)
    useragent (0.16.11)
    warden (1.2.9)
      rack (>= 2.0.9)
    web-console (4.2.1)
      actionview (>= 6.0.0)
      activemodel (>= 6.0.0)
      bindex (>= 0.4.0)
      railties (>= 6.0.0)
    websocket (1.2.11)
    websocket-driver (0.7.6)
      websocket-extensions (>= 0.1.0)
    websocket-extensions (0.1.5)
    xpath (3.2.0)
      nokogiri (~> 1.8)
    zeitwerk (2.7.1)

PLATFORMS
  aarch64-linux
  arm-linux
  arm64-darwin-23
  x86-linux
  x86_64-darwin
  x86_64-linux

DEPENDENCIES
  activeadmin (~> 4.0.0.beta7)
  aws-sdk-s3 (~> 1.176)
  bootsnap
  brakeman
  bundler-audit
  capybara
  cssbundling-rails
  database_consistency
  debug
  devise
  devise-i18n
  dockerfile-rails (>= 1.6)
  erb_lint
  fancy_irb (~> 2.1)
  hotwire_combobox
  importmap-rails
  jbuilder
  kamal
  kaminari-i18n
  overmind
  pg (~> 1.1)
  propshaft
  puma (>= 5.0)
  pundit
  rails (~> 8.0.0)
  rails-i18n
  rubocop-capybara
  selenium-webdriver
  solid_cable
  solid_cache
  solid_queue
  stimulus-rails
  stylecheck!
  thruster
  turbo-rails
  tzinfo-data
  web-console

RUBY VERSION
   ruby 3.3.4p94

BUNDLED WITH
   2.5.15
```

</details>

**Comment by mattbrictson** [comment]
Thanks! I might not get to this right away, but in the meantime it sounds like running `bundle install` first is a workaround?

**Comment by vfonic** [comment]
Yes, you're right. `bundle install` fixes the issue. It was just a happenstance that I didn't have the exact `reline` gem version from the `Gemfile.lock` installed.

**Comment by mattbrictson** [comment]
OK, I see what is going on here. Internally, `update-interactive` calls `bundle outdated --parseable` with a specific list of gems. E.g.:

```
bundle outdated --parseable pg rails activeadmin fancy_irb
```

That command fails with:

```
Could not find reline-0.5.12 in locally installed gems
```

However, without any gems listed, `bundle outdated --parseable` runs fine.

I'll report this upstream, since it seems like a bug with Bundler itself.

As an interim fix, I could change `update-interactive` to use the non-specific version of `outdated` (i.e. not pass gem arguments), but this would make things slower, as Bundler would have to check for outdated versions of *all* gems in the lock file, not just the ones we care about. I'd rather not do that, so hopefully this issue can be fixed in Bundler itself.

In the meantime, running `bundle install` is a simple workaround.

**Comment by mattbrictson** [comment]
Upstream issue: https://github.com/rubygems/rubygems/issues/8349

**Comment by vfonic** [comment]
I can't repro this anymore.

I upgraded to Ruby 3.4.1 and it seems like reline is one of the default gems now so I cannot uninstall it.

I don't have any lower Ruby versions on my machine. I tested and `bundle ui` didn't fail even after I tried to uninstall reline:

```
 > gem uninstall reline

You have requested to uninstall the gem:
        reline-0.6.0

debug-1.10.0 depends on reline (>= 0.3.8)
debug-1.9.2 depends on reline (>= 0.3.8)
highline-3.1.0 depends on reline (>= 0)
irb-1.14.3 depends on reline (>= 0.4.2)
irb-1.14.3 depends on reline (>= 0.4.2)
irb-1.14.1 depends on reline (>= 0.4.2)
irb-1.14.0 depends on reline (>= 0.4.2)
readline-0.0.4 depends on reline (>= 0)
If you remove this gem, these dependencies will not be met.
Continue with Uninstall? [yN]  y
Successfully uninstalled reline-0.6.0
There was both a regular copy and a default copy of reline-0.6.0. The regular copy was successfully uninstalled, but the default copy was left around because default gems can't be removed.
```

> There was both a regular copy and a default copy of reline-0.6.0. The regular copy was successfully uninstalled, but the default copy was left around because default gems can't be removed.

I think this issue can be closed.
